language: python

python:
  - 3.5
  - 3.6

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
    - $HOME/.pre-commit
    - $HOME/Library/Caches/Homebrew

env:
  global:
    - BUILD_PATH=pages-build

matrix:
  fast_finish: true

  include:
    - python: 3.7
      sudo: required
      dist: xenial
    - python: nightly
      sudo: required
      dist: xenial

    # OSX
    - os: osx
      python: 3.5
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.5.6
    - os: osx
      python: 3.6
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.6.6
    - os: osx
      python: 3.7
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.7.0

  allow_failures:
    - python: nightly
      sudo: required
      dist: xenial

install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo ${TRAVIS_PYTHON_VERSION}
      brew upgrade -y pyenv openssl
      eval "$(pyenv init -)"
      pyenv install --skip-existing --keep --verbose ${TRAVIS_PYTHON_VERSION}
      pyenv shell ${TRAVIS_PYTHON_VERSION}
      python -V
    fi
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt

script:
  - make html
  - mkdir -p ${BUILD_PATH}
  - cp -Rv build/* $BUILD_PATH
  - cp -Rv docs/* $BUILD_PATH

before_cache:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew --cache
    fi
