language: python

python:
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - doxygen

cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
    - $HOME/.pre-commit
    - $HOME/Library/Caches/Homebrew
    - $HOME/.ccache

env:
  global:
    - BUILD_PATH=pages-build

matrix:
  fast_finish: true

  include:
    - python: 3.7
      sudo: required
      dist: xenial
    - python: nightly
      sudo: required
      dist: xenial

    # OSX
    - os: osx
      python: 3.5
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.5.6
    - os: osx
      python: 3.6
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.6.6
    - os: osx
      python: 3.7
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.7.0

  allow_failures:
    - python: nightly
      sudo: required
      dist: xenial

install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo ${TRAVIS_PYTHON_VERSION}
      brew upgrade -y pyenv openssl
      eval "$(pyenv init -)"
      pyenv install --skip-existing --keep --verbose ${TRAVIS_PYTHON_VERSION}
      pyenv shell ${TRAVIS_PYTHON_VERSION}
      brew install -y https://raw.githubusercontent.com/Homebrew/homebrew-core/5b680fb58fedfb00cd07a7f69f5a621bb9240f3b/Formula/doxygen.rb;
    fi
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
  - python -V
  - doxygen --version

script:
  - make html
  - python rebuild_readme.py
  - mkdir -p ${BUILD_PATH}
  - cp -Rv build/* $BUILD_PATH
  - cp -Rv docs/* $BUILD_PATH

before_cache:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew --cache
    fi
